README.md, docs/docs/getting-started/installing-fluttium.md, docs/docusaurus.config.js, packages/fluttium_cli/example/README.md, packages/fluttium_cli/lib/src/command_runner.dart, packages/fluttium_flow/README.md, packages/fluttium_flow/lib/fluttium_flow.dart, packages/fluttium_flow/pubspec.yaml, packages/fluttium_runner/example/README.md
=> chore: fix tag line

packages/fluttium_cli/lib/src/command_runner.dart, packages/fluttium_cli/lib/src/version.dart, packages/fluttium_cli/test/src/command_runner_test.dart, tools/release_ready.sh
=> fix: using wrong `packageVersion` in the version check

packages/fluttium_cli/CHANGELOG.md, packages/fluttium_cli/lib/src/version.dart, packages/fluttium_cli/pubspec.yaml
**READY**
Release v0.1.0-dev.4
=> chore(fluttium_cli): v0.1.0-dev.4

packages/fluttium_runner/CHANGELOG.md, packages/fluttium_runner/pubspec.yaml
**READY**
Release v0.1.0-dev.2
=> chore(fluttium_runner): v0.1.0-dev.2

packages/fluttium_cli/pubspec.yaml
**READY**
Upgrade `fluttium_runner` to 0.1.0-dev.2
=> chore(fluttium_cli): upgrade `fluttium_runner` to 0.1.0-dev.2

packages/fluttium_cli/CHANGELOG.md, packages/fluttium_cli/lib/src/version.dart, packages/fluttium_cli/pubspec.yaml
**READY**
Release v0.1.0-dev.5
=> chore(fluttium_cli): v0.1.0-dev.5

packages/fluttium_runner/lib/src/fluttium_runner.dart
=> fix(fluttium_runner): last action not executed

packages/fluttium_runner/CHANGELOG.md, packages/fluttium_runner/pubspec.yaml
=> chore(fluttium_runner): v0.1.0-dev.3

packages/fluttium_cli/pubspec.yaml
Upgrade `fluttium_runner` to v0.1.0-dev.3
=> chore(fluttium_cli): upgrade `fluttium_runner` to 0.1.0-dev.3

packages/fluttium_cli/CHANGELOG.md, packages/fluttium_cli/lib/src/version.dart, packages/fluttium_cli/pubspec.yaml
=> chore(fluttium_cli): v0.1.0-dev.6

packages/fluttium_runner/lib/src/bundles/fluttium_driver_bundle.dart, packages/fluttium_runner/lib/src/fluttium_runner.dart
=> fix: sanitize text representations

packages/fluttium_runner/CHANGELOG.md, packages/fluttium_runner/pubspec.yaml
**READY**
Release v0.1.0-dev.4 of Fluttium Runner
=> chore(fluttium_runner): v0.1.0-dev.4

packages/fluttium_cli/CHANGELOG.md, packages/fluttium_cli/lib/src/version.dart, packages/fluttium_cli/pubspec.yaml
**READY**
Release `fluttium_cli` v0.1.0-dev.7
=> chore(fluttium_cli): v0.1.0-dev.7

docs/docs/cli/test-command.md
=> docs: add flavor and target documentation

packages/fluttium_cli/lib/src/commands/test_command.dart, packages/fluttium_cli/test/src/commands/test_command_test.dart
READY
Should mitigate #29 a bit.
See also:
- https://github.com/flutter/flutter/issues/59533#issuecomment-648432478
=> fix: run `flutter` without version check

docs/docs/why-fluttium.md
=> docs: list supported platforms

.github/actions/dart_package/action.yaml, .github/actions/docs/action.yaml, .github/actions/pana/action.yaml, .github/workflows/docs.yaml, .github/workflows/main.yaml, docs/docs/actions/expectations.md, docs/docs/actions/gestures.md, packages/fluttium_cli/lib/fluttium_cli.dart
**READY**
Removes the `key` references as we wont implement those as mentioned in #6
=> docs: remove `key` references

docs/docs/why-fluttium.md, docs/src/pages/index.tsx
=> docs: make it more clear what the goal of Fluttium is

docs/docs/actions/expectations.md, docs/docs/actions/gestures.md
=> docs: fix key references

.github/cspell.json, .github/workflows/main.yaml, packages/fluttium_cli/lib/fluttium_cli.dart
=> ci: add spell check

docs/docs/why-fluttium.md
=> docs: fix `og` description of the why section

packages/fluttium_cli/CHANGELOG.md, packages/fluttium_cli/lib/src/version.dart, packages/fluttium_cli/pubspec.yaml
**READY**
Release of v0.1.0-dev.8 of Fluttium CLI
=> chore(fluttium_cli): v0.1.0-dev.8

packages/fluttium_cli/lib/src/commands/test_command.dart, packages/fluttium_flow/lib/fluttium_flow.dart, packages/fluttium_flow/lib/src/json_decode_safely.dart, packages/fluttium_flow/test/src/json_decode_safely_test.dart, packages/fluttium_runner/lib/src/fluttium_runner.dart
**READY**
Fixes #29 and makes getting JSON's more safe overal.
=> fix: unexpected end of input error when running fluttium test

packages/fluttium_flow/CHANGELOG.md, packages/fluttium_flow/README.md, packages/fluttium_flow/lib/fluttium_flow.dart, packages/fluttium_flow/pubspec.yaml
Release v0.1.0-dev.2 of `flutterium_flow`
=> chore(fluttium_flow): 0.1.0-dev.2

packages/fluttium_runner/CHANGELOG.md, packages/fluttium_runner/pubspec.yaml
**READY**
Release v0.1.0-dev.5 of `fluttium_runner`
=> chore(fluttium_runner): 0.1.0-dev.5

packages/fluttium_cli/CHANGELOG.md, packages/fluttium_cli/lib/src/version.dart, packages/fluttium_cli/pubspec.yaml
**READY**
Release v0.1.0-dev.9 of `fluttium_cli`
=> chore(fluttium_cli): 0.1.0-dev.9

packages/fluttium_cli/lib/src/command_runner.dart, packages/fluttium_cli/lib/src/commands/update_command.dart, packages/fluttium_cli/test/src/command_runner_test.dart
**READY**
Fix update prompt on update
=> fix: update prompt on update

tools/release_ready.sh
=> chore: improve release tool

packages/fluttium_runner/CHANGELOG.md, packages/fluttium_runner/pubspec.yaml
=> chore(fluttium_runner): 0.1.0-dev.6

packages/fluttium_cli/pubspec.yaml
=> chore(fluttium_cli): update `fluttium_runner` to v0.1.0-dev.6

packages/fluttium_cli/CHANGELOG.md, packages/fluttium_cli/lib/src/version.dart, packages/fluttium_cli/pubspec.yaml
**READY**
Release v0.1.0-dev.10 of `fluttium_cli`
=> chore(fluttium_cli): 0.1.0-dev.10

.gitignore, .idea/runConfigurations/development.xml, .idea/runConfigurations/production.xml, .idea/runConfigurations/staging.xml, .vscode/launch.json, example/.gitignore
=> chore: un-ignore launch files

packages/fluttium_cli/lib/src/commands/test_command.dart, packages/fluttium_cli/lib/src/flutter_device.dart
**READY**
On Windows devices like `edge` can be reported, but they are missing a `targetPlatform` and a `isSupported` data entry, so to ensure we dont show devices that we cant run on we set it to false if it is missing and filter based on it.
=> feat: ensure only supported devices show up

docs/docs/why-fluttium.md, packages/fluttium_cli/lib/src/commands/test_command.dart, packages/fluttium_cli/test/src/commands/test_command_test.dart
**READY**
Support the windows platform
Closes #13
=> feat: support windows platform

docs/docs/why-fluttium.md, packages/fluttium_cli/lib/src/commands/test_command.dart, packages/fluttium_cli/test/src/commands/test_command_test.dart, packages/fluttium_runner/lib/src/fluttium_runner.dart
**READY**
Add support for the Linux platform to Fluttium.
Closes #14
=> feat: support linux platform

packages/fluttium_runner/CHANGELOG.md, packages/fluttium_runner/pubspec.yaml
=> chore(fluttium_runner): 0.1.0-dev.7

packages/fluttium_cli/pubspec.yaml
Update `fluttium_runner` to v0.1.0-dev.7
=> chore(fluttium_cli): update `fluttium_runner` to v0.1.0-dev.7

packages/fluttium_cli/CHANGELOG.md, packages/fluttium_cli/lib/src/version.dart, packages/fluttium_cli/pubspec.yaml
**READY**
Release v0.1.0-dev.11 of the Fluttium CLI
=> chore(fluttium_cli): 0.1.0-dev.11

packages/fluttium_runner/CHANGELOG.md, packages/fluttium_runner/pubspec.yaml
**READY**
Release v0.1.0-dev.8 of `fluttium_runner`
=> chore(fluttium_runner): 0.1.0-dev.8

packages/fluttium_cli/pubspec.yaml
**READY**
Update `fluttium_runner` to v0.1.0-dev.8
=> chore(fluttium_cli): update `fluttium_runner` to v0.1.0-dev.8

packages/fluttium_cli/CHANGELOG.md, packages/fluttium_cli/lib/src/version.dart, packages/fluttium_cli/pubspec.yaml
**READY**
Release v0.1.0-dev.12 of `fluttium_cli`
=> chore(fluttium_cli): 0.1.0-dev.12

packages/fluttium_runner/CHANGELOG.md, packages/fluttium_runner/pubspec.yaml
**READY**
Release v0.1.0-dev.9 of `fluttium_runner`
=> chore(fluttium_runner): 0.1.0-dev.9

packages/fluttium_cli/pubspec.yaml
**READY**
Update `fluttium_runner` to v0.1.0-dev.9
=> chore(fluttium_cli): update `fluttium_runner` to v0.1.0-dev.9

packages/fluttium_cli/CHANGELOG.md, packages/fluttium_cli/lib/src/version.dart, packages/fluttium_cli/pubspec.yaml
**READY**
Release v0.1.0-dev.13 of the `fluttium_cli`
=> chore(fluttium_cli): 0.1.0-dev.13

bricks/fluttium_flow/__brick__/{{name}}.yaml, packages/fluttium_cli/lib/src/bundles/fluttium_flow_bundle.dart
**READY**
Steps and descriptions were being escaped in the create command.
=> fix: don't escape steps in flow brick

example/flows/drawer_flow.yaml, example/lib/app/view/app.dart, example/lib/drawer/cubit/drawer_cubit.dart, example/lib/drawer/drawer.dart, example/lib/drawer/view/drawer_page.dart, example/test/app/view/app_test.dart, example/test/drawer/cubit/drawer_cubit_test.dart, example/test/drawer/view/drawer_page_test.dart
**READY**
Add a drawer example
=> chore: add drawer example

packages/fluttium_runner/CHANGELOG.md, packages/fluttium_runner/pubspec.yaml
**READY**
Release v0.1.0-dev.10 of `fluttium_runner`
=> chore(fluttium_runner): 0.1.0-dev.10

packages/fluttium_cli/pubspec.yaml
**READY**
Update `fluttium_runner` to v0.1.0-dev.10
=> chore(fluttium_cli): update `fluttium_runner` to v0.1.0-dev.10

packages/fluttium_cli/CHANGELOG.md, packages/fluttium_cli/lib/src/version.dart, packages/fluttium_cli/pubspec.yaml
**READY**
Release v0.1.0-dev.14 of `fluttium_cli`
=> chore(fluttium_cli): 0.1.0-dev.14

packages/fluttium_runner/CHANGELOG.md, packages/fluttium_runner/pubspec.yaml
**READY**
Release v0.1.0-dev.11 of `fluttium_runner
=> chore(fluttium_runner): 0.1.0-dev.11

packages/fluttium_cli/pubspec.yaml
**READY**
Update `fluttium_runner` to v0.1.0-dev.11
=> chore(fluttium_cli): update `fluttium_runner` to v0.1.0-dev.11

packages/fluttium_cli/CHANGELOG.md, packages/fluttium_cli/lib/src/version.dart, packages/fluttium_cli/pubspec.yaml
**READY**
Release v0.1.0-dev.15 of the `fluttium_cli`
=> chore(fluttium_cli): 0.1.0-dev.15

.github/workflows/main.yaml, .gitignore, LICENSE, README.md, actions/log_action/.gitignore, actions/log_action/CHANGELOG.md, actions/log_action/LICENSE, actions/log_action/README.md, actions/log_action/analysis_options.yaml, actions/log_action/example/README.md, actions/log_action/lib/log_action.dart, actions/log_action/lib/src/log_action.dart, actions/log_action/pubspec.yaml, actions/log_action/pubspec_overrides.yaml, actions/log_action/test/register_test.dart, actions/log_action/test/src/log_action_test.dart, tools/setup_local_development.sh
**READY**
Add a simple log action, which will be included in newly created `fluttium.yaml` files.
=> feat: add simple log action

bricks/fluttium_action/__brick__/{{name.snakeCase()}}/pubspec.yaml, bricks/fluttium_action/brick.yaml, packages/fluttium_cli/lib/src/bundles/fluttium_action_bundle.dart, packages/fluttium_cli/lib/src/commands/init_command.dart, packages/fluttium_cli/lib/src/commands/new_command/new_bundle_command.dart, packages/fluttium_cli/lib/src/commands/new_command/new_command.dart, packages/fluttium_cli/test/fixtures/new/action/my_action/pubspec.yaml, packages/fluttium_driver/lib/src/fluttium_driver.dart, packages/fluttium_interfaces/test/src/fluttium/fluttium_yaml_test.dart
=> feat: make version management easier

actions/log_action/README.md, actions/log_action/test/register_test.dart, example/README.md
=> docs: update READMEs with badge

cspell.json, example/flows/complex_text.yaml, example/flows/counter_flow.yaml, example/flows/drawer_flow.yaml, example/flows/progress_flow.yaml, example/flows/simple_menu_flow.yaml, example/flows/text_flow.yaml, example/lib/app/view/app.dart, example/lib/simple_menu/simple_menu.dart, example/lib/simple_menu/view/simple_menu.dart, example/test/app/view/app_test.dart, example/test/simple_menu/view/simple_menu_test.dart, packages/fluttium/example/main.dart, packages/fluttium/lib/src/actions/actions.dart, packages/fluttium/lib/src/actions/long_press_on.dart, packages/fluttium/lib/src/actions/long_tap_on.dart, packages/fluttium/lib/src/actions/press_on.dart, packages/fluttium/lib/src/registry.dart, packages/fluttium/test/src/actions/long_press_on_test.dart, packages/fluttium/test/src/actions/long_tap_on_test.dart, packages/fluttium/test/src/actions/press_on_test.dart, packages/fluttium_driver/test/src/fluttium_driver_test.dart, packages/fluttium_interfaces/example/main.dart, packages/fluttium_interfaces/test/src/user_flow/user_flow_step_test.dart, packages/fluttium_interfaces/test/src/user_flow/user_flow_yaml_test.dart
**READY**
Implement a `longPressOn` action.
Closes #3
=> feat: implement a `LongPressOn` action

packages/fluttium/lib/src/actions/actions.dart, packages/fluttium/lib/src/actions/input_text.dart, packages/fluttium/lib/src/actions/write_text.dart, packages/fluttium/lib/src/registry.dart, packages/fluttium/lib/src/text_input_controller.dart, packages/fluttium/test/src/actions/input_text_test.dart, packages/fluttium/test/src/actions/write_text_test.dart, packages/fluttium/test/src/text_input_controller_test.dart
**READY**
The `InputText` currently replace any text in any field, this PR will allow it to only replace if specified otherwise it will append.
=> feat: implement `WriteText` action

.vscode/launch.json, packages/fluttium/lib/src/actions/long_press_on.dart, packages/fluttium/lib/src/actions/press_on.dart, packages/fluttium/lib/src/registry.dart, packages/fluttium/test/src/actions/long_press_on_test.dart, packages/fluttium/test/src/actions/press_on_test.dart, packages/fluttium_cli/lib/src/commands/init_command.dart, packages/fluttium_cli/test_fixtures/init/fluttium.yaml
=> chore: clean up some code smells

CONTRIBUTING.md, README.md
=> docs: add `CONTRIBUTING` document

.github/workflows/pub_publish.yaml
=> ci: update pub publish

actions/log_action/pubspec.yaml, packages/fluttium/pubspec.yaml, packages/fluttium_cli/pubspec.yaml, packages/fluttium_driver/pubspec.yaml, packages/fluttium_interfaces/pubspec.yaml, packages/fluttium_protocol/pubspec.yaml
=> chore: fix repository url

packages/fluttium_protocol/CHANGELOG.md
**READY**
Release v0.1.0-dev.1 of `fluttium_protocol`
=> chore(fluttium_protocol): 0.1.0-dev.1

.github/workflows/pub_publish.yaml
=> ci: fix publish workflow

.github/workflows/pub_publish.yaml
=> ci: fix publish workflow (#164

.github/workflows/pub_publish.yaml, packages/fluttium_interfaces/CHANGELOG.md
=> chore(fluttium_interfaces): 0.1.0-dev.1

packages/fluttium/CHANGELOG.md
=> chore(fluttium): 0.1.0-dev.1

.github/workflows/pub_publish.yaml
=> ci: use flutter for publish

packages/fluttium_driver/CHANGELOG.md
=> chore(fluttium_driver): 0.1.0-dev.1

.github/workflows/pub_publish.yaml, actions/log_action/CHANGELOG.md
=> chore(log_action): 0.1.0-dev.1 (#170

bricks/fluttium_flow/brick.yaml
=> chore(fluttium_flow): 0.1.0

packages/fluttium_cli/CHANGELOG.md, packages/fluttium_cli/lib/src/version.dart, packages/fluttium_cli/pubspec.yaml, packages/fluttium_cli/test/src/commands/new_command/new_bundle_command_test.dart
=> chore(fluttium_cli): 0.1.0-dev.16 (#173

packages/fluttium_cli/.pubignore
=> chore: add pubignore

docs/docs/actions/built-in/debugging.md
**READY**
Add docs about actions for debugging
=> docs: add debugging docs (#175

bricks/fluttium_launcher/brick.yaml, bricks/fluttium_test_runner/brick.yaml
=> chore: change brick `publish_to` to none

packages/fluttium_interfaces/lib/src/fluttium/driver_configuration.dart, packages/fluttium_interfaces/test/src/fluttium/driver_configuration_test.dart, packages/fluttium_interfaces/test/src/fluttium/fluttium_yaml_test.dart
=> feat: use snake case syntax for driver configuration

packages/fluttium_interfaces/CHANGELOG.md, packages/fluttium_interfaces/pubspec.yaml
=> chore(fluttium_interfaces): 0.1.0-dev.2

bricks/fluttium_launcher/__brick__/.{{runner_id}}_launcher.dart, bricks/fluttium_launcher/brick.yaml, packages/fluttium_driver/example/main.dart, packages/fluttium_driver/lib/src/bundles/fluttium_launcher_bundle.dart, packages/fluttium_driver/lib/src/bundles/fluttium_test_runner_bundle.dart, packages/fluttium_driver/lib/src/fluttium_driver.dart, packages/fluttium_driver/pubspec.yaml, packages/fluttium_driver/test/src/fluttium_driver_test.dart
=> chore(fluttium_driver): update `fluttium_interfaces` version

packages/fluttium_driver/CHANGELOG.md, packages/fluttium_driver/pubspec.yaml
=> chore(fluttium_driver): 0.1.0-dev.2

docs/docs/getting-started/initializing-fluttium.md, example/fluttium.yaml, packages/fluttium_cli/lib/src/bundles/fluttium_action_bundle.dart, packages/fluttium_cli/lib/src/bundles/fluttium_flow_bundle.dart, packages/fluttium_cli/lib/src/commands/init_command.dart, packages/fluttium_cli/lib/src/commands/test_command.dart, packages/fluttium_cli/pubspec.yaml, packages/fluttium_cli/test/src/commands/test_command_test.dart, packages/fluttium_cli/test_fixtures/init/fluttium.yaml
=> fix: driver configuration is not being read correctly from `fluttium.yaml`

docs/docs/actions/built-in/advanced.md, packages/fluttium/lib/src/actions/actions.dart, packages/fluttium/lib/src/actions/wait.dart, packages/fluttium/lib/src/registry.dart, packages/fluttium/test/src/actions/clear_text_test.dart, packages/fluttium/test/src/actions/wait_test.dart
**IN DEVELOPMENT**
Implement a `Wait` action.
Closes #71
=> feat: implement a `Wait` action

packages/fluttium/CHANGELOG.md, packages/fluttium/pubspec.yaml
=> chore(fluttium): 0.1.0-dev.2

.github/workflows/main.yaml, packages/fluttium_driver/lib/src/fluttium_driver.dart, packages/fluttium_driver/test/src/fluttium_driver_test.dart
**READY**
Support path for actions on windows
=> fix(fluttium_driver): support path for actions on windows (#193

packages/fluttium_driver/CHANGELOG.md, packages/fluttium_driver/pubspec.yaml
**READY**
Release v0.1.0-dev.3 of `fluttium_driver`
=> chore(fluttium_driver): 0.1.0-dev.3

packages/fluttium_cli/lib/src/commands/test_command.dart, packages/fluttium_cli/test/src/commands/test_command_test.dart
**READY**
Should always use given device (`--device`) instead of prompting
=> fix(fluttium_cli): always use given device instead of prompting

packages/fluttium_cli/pubspec.yaml
=> chore(fluttium_cli): update `fluttium_driver` to v0.1.0-dev.3

packages/fluttium_cli/CHANGELOG.md, packages/fluttium_cli/lib/src/version.dart, packages/fluttium_cli/pubspec.yaml
=> chore(fluttium_cli): 0.1.0-dev.18

docs/src/pages/index.tsx
=> docs: rephrase to multi-platform

docs/src/pages/index.tsx
=> docs: change phrasing of the multi-platform section

packages/fluttium/lib/src/registry.dart, packages/fluttium/test/src/registry_test.dart
**READY**
Adding support for aliasing parameter names for actions.
=> feat(fluttium): support aliasing parameter names for actions (#217

packages/fluttium/CHANGELOG.md, packages/fluttium/pubspec.yaml
**READY**
Release v0.1.0-dev.3
=> chore(fluttium): 0.1.0-dev.3

docs/docs/actions/built-in/interactions.md
=> docs: fix alias mistake

packages/fluttium_cli/lib/src/commands/test_command/reporters/pretty_reporter.dart, packages/fluttium_cli/lib/src/commands/test_command/test_command.dart, packages/fluttium_cli/test/src/commands/test_command/test_command_test.dart
=> fix(fluttium_cli): `expanded` reporter not storing screenshots

packages/fluttium/lib/src/actions/clear_text.dart, packages/fluttium/lib/src/actions/write_text.dart, packages/fluttium/lib/src/extensions/semantics_node.dart, packages/fluttium/lib/src/tester.dart, packages/fluttium/pubspec.yaml, packages/fluttium/test/src/tester_test.dart
**READY**
Migrate to Flutter 3.10.0
=> feat(fluttium)!: migrate to Flutter v3.10.0

packages/fluttium/CHANGELOG.md, packages/fluttium/pubspec.yaml
**READY**
Release v0.1.0 of `fluttium`
=> chore(fluttium): 0.1.0

actions/log_action/pubspec.yaml, bricks/fluttium_action/__brick__/{{name.snakeCase()}}/pubspec.yaml, example/actions/expect_environment_text/pubspec.yaml, example/lib/complex_text/view/complex_text_page.dart, example/lib/simple_menu/view/simple_menu.dart, example/pubspec.yaml, packages/fluttium/pubspec.yaml, packages/fluttium_cli/lib/src/bundles/fluttium_action_bundle.dart, packages/fluttium_cli/pubspec.yaml, packages/fluttium_cli/test/src/command_runner_test.dart, packages/fluttium_cli/test/src/commands/test_command/test_command_test.dart, packages/fluttium_cli/test/src/commands/update_command_test.dart, packages/fluttium_cli/test_fixtures/new/action/my_action/pubspec.yaml, packages/fluttium_driver/pubspec.yaml, packages/fluttium_interfaces/lib/src/fluttium/driver_configuration.dart, packages/fluttium_interfaces/pubspec.yaml, packages/fluttium_protocol/pubspec.yaml, packages/fluttium_protocol/test/src/listener_test.dart, tools/pubspec.yaml
**READY**
Bump dart version to 3.0.0
=> chore: bump dart version to 3.0.0

packages/fluttium_interfaces/CHANGELOG.md, packages/fluttium_interfaces/pubspec.yaml
**READY**
Release `fluttium_interfaces`
=> chore(fluttium_interfaces): 0.1.0

packages/fluttium_protocol/CHANGELOG.md, packages/fluttium_protocol/pubspec.yaml
**READY**
Release `fluttium_protocol`
=> chore(fluttium_protocol): 0.1.0

bricks/fluttium_action/CHANGELOG.md, bricks/fluttium_action/brick.yaml
**READY**
Release `fluttium_action`
=> chore(fluttium_action): 0.2.0

packages/fluttium/pubspec.yaml
=> chore(fluttium): bump versions

packages/fluttium_driver/pubspec.yaml
=> chore(fluttium_driver): bump versions

bricks/fluttium_test_runner/__brick__/pubspec.yaml, packages/fluttium/pubspec.yaml, packages/fluttium_driver/lib/src/bundles/fluttium_test_runner_bundle.dart
=> fix: remove Flutter upper bound constraint

packages/fluttium_driver/CHANGELOG.md, packages/fluttium_driver/pubspec.yaml
**READY**
Release v0.1.0 of `fluttium_driver`
=> chore(fluttium_driver): 0.1.0

actions/log_action/pubspec.yaml
=> chore(log_action): bump fluttium version

actions/log_action/CHANGELOG.md, actions/log_action/pubspec.yaml
**READY**
Release v0.2.0 of `log_action`
=> chore(log_action): 0.2.0

packages/fluttium_cli/lib/src/command_runner.dart, packages/fluttium_cli/test/helpers/with_runner.dart, packages/fluttium_cli/test/src/command_runner_test.dart, packages/fluttium_cli/test/src/commands/init_command_test.dart, packages/fluttium_cli/test/src/commands/new_command/new_command_test.dart, packages/fluttium_cli/test/src/commands/test_command/test_command_test.dart, packages/fluttium_cli/test/src/commands/update_command_test.dart
**READY**
Check the installed Flutter version to see if the CLI supports it or not.
=> feat(fluttium_cli): check if installed Flutter version is supported

bricks/fluttium_test_runner/__brick__/pubspec.yaml, packages/fluttium_driver/lib/src/bundles/fluttium_test_runner_bundle.dart
=> fix(fluttium_driver): use correct fluttium constraints

packages/fluttium_driver/CHANGELOG.md, packages/fluttium_driver/pubspec.yaml
=> chore(fluttium_driver): 0.1.1

example/fluttium.yaml, packages/fluttium_cli/pubspec.yaml, packages/fluttium_cli/test/src/commands/test_command/test_command_test.dart, packages/fluttium_cli/test_fixtures/init/fluttium.yaml, packages/fluttium_cli/test_fixtures/new/action/my_action/pubspec.yaml, packages/fluttium_interfaces/example/main.dart, packages/fluttium_interfaces/test/src/fluttium/fluttium_environment_test.dart, packages/fluttium_interfaces/test/src/fluttium/fluttium_yaml_test.dart
=> chore(fluttium_cli): bump `fluttium_driver` version

packages/fluttium_cli/lib/src/commands/init_command.dart, packages/fluttium_cli/test_fixtures/init/fluttium.yaml
=> fix(fluttium_cli): use correct `log_action` version in `fluttium.yaml`

packages/fluttium_cli/CHANGELOG.md, packages/fluttium_cli/lib/src/version.dart, packages/fluttium_cli/pubspec.yaml
**READY**
Release v0.1.0 of `fluttium_cli`
=> chore(fluttium_cli): 0.1.0

docs/docs/actions/custom.md, docs/docs/getting-started/initializing-fluttium.md
=> docs: update docs for v0.1.0

packages/fluttium_cli/lib/src/commands/test_command/test_command.dart, packages/fluttium_cli/test/src/commands/test_command/test_command_test.dart
**READY**
Fix an issue that was introduced on accident in #243
=> fix(fluttium_cli): use last step that is done for storing files

bricks/fluttium_test_runner/__brick__/pubspec.yaml, example/fluttium.yaml, packages/fluttium_cli/test/src/commands/test_command/test_command_test.dart, packages/fluttium_cli/test_fixtures/init/fluttium.yaml, packages/fluttium_driver/lib/src/bundles/fluttium_test_runner_bundle.dart, packages/fluttium_interfaces/example/main.dart, packages/fluttium_interfaces/test/src/fluttium/fluttium_environment_test.dart, packages/fluttium_interfaces/test/src/fluttium/fluttium_yaml_test.dart
**READY**
The version constraint for Fluttium was too strict.
=> fix: adjust fluttium version constraints

packages/fluttium_driver/CHANGELOG.md, packages/fluttium_driver/pubspec.yaml
=> chore(fluttium_driver): 0.1.2

packages/fluttium_cli/CHANGELOG.md, packages/fluttium_cli/lib/src/version.dart, packages/fluttium_cli/pubspec.yaml
=> chore(fluttium_cli): 0.1.1

packages/fluttium_cli/lib/src/commands/new_command/new_bundle_command.dart, packages/fluttium_cli/pubspec.yaml, packages/fluttium_driver/pubspec.yaml
**READY**
Fixes non_exhaustive_switch_statement violation. Fixes #302
=> chore: updated `mason` dependency to v0.1.0-dev.50

packages/fluttium_driver/CHANGELOG.md, packages/fluttium_driver/pubspec.yaml
=> chore(fluttium_driver): 0.1.3

README.md
Found that the commands in the README were outdated. 
**READY**
Updated the commands, and reformatted the tables.  
Does not really fix #306 but is slightly related.
=> docs: reformatted tables and updated commands in README.md

packages/fluttium_cli/CHANGELOG.md, packages/fluttium_cli/lib/src/version.dart, packages/fluttium_cli/pubspec.yaml
=> chore(fluttium_cli): 0.1.2
